name: Deploy React App to gh-pages

on:
  push:
    branches:
      - master  # Adjust to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Using v4 for checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Using v4 for Node.js setup
        with:
          node-version: '16'  # Change to your Node.js version if different

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to gh-pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the push
